server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/school_client?useUnicode=true&characterEncoding=utf8
    username: root
    password: admin
    driver-class-name: com.mysql.jdbc.Driver




